"""LinkedIn Poster — generates sales post drafts and simulates publishing.

Creates approval requests for all posts. In dry-run mode, logs the post
instead of publishing. In live mode, uses Playwright for LinkedIn posting.
"""

import argparse
import os
from datetime import datetime

from dotenv import load_dotenv

from src.utils.file_ops import create_task_file, get_folder
from src.utils.logger import log_action, log_error

load_dotenv()

DRY_RUN = os.getenv("DRY_RUN", "true").lower() == "true"


# === Post Templates ===

POST_TEMPLATES = {
    "thought_leadership": {
        "structure": [
            "Hook: Bold statement or surprising statistic",
            "Story: Personal experience or case study",
            "Insight: The key takeaway or lesson",
            "CTA: Question to drive engagement",
        ],
        "hashtags": ["#AIAutomation", "#ThoughtLeadership", "#Innovation"],
    },
    "case_study": {
        "structure": [
            "Hook: The result or transformation",
            "Problem: What the challenge was",
            "Solution: What was done",
            "Results: Specific metrics or outcomes",
            "CTA: Invitation to learn more",
        ],
        "hashtags": ["#CaseStudy", "#Results", "#BusinessGrowth"],
    },
    "tips_and_tricks": {
        "structure": [
            "Hook: Promise of value (X tips for Y)",
            "Tips: Numbered list of actionable advice",
            "Bonus: One extra insight",
            "CTA: Ask which tip resonates most",
        ],
        "hashtags": ["#Tips", "#Productivity", "#BusinessTips"],
    },
    "industry_news": {
        "structure": [
            "Hook: The news headline",
            "Context: Why this matters",
            "Take: Your unique perspective",
            "CTA: Ask for others' opinions",
        ],
        "hashtags": ["#IndustryNews", "#AI", "#TechTrends"],
    },
}


def create_post_draft(
    topic: str,
    template_type: str = "thought_leadership",
    content: str = "",
    audience: str = "Business leaders and tech enthusiasts",
) -> dict:
    """Create a LinkedIn post draft and route to approval.

    Returns dict with file path and metadata.
    """
    template = POST_TEMPLATES.get(template_type, POST_TEMPLATES["thought_leadership"])

    metadata = {
        "type": "sales_post",
        "platform": "linkedin",
        "template": template_type,
        "topic": topic,
        "target_audience": audience,
        "status": "draft",
        "priority": "medium",
        "requires_approval": True,
    }

    body = f"# LinkedIn Post Draft: {topic}\n\n"
    body += f"**Template:** {template_type}\n"
    body += f"**Audience:** {audience}\n"
    body += f"**Suggested Time:** Friday 4:00 PM\n\n"

    body += "## Structure\n\n"
    for i, section in enumerate(template["structure"], 1):
        body += f"{i}. {section}\n"

    if content:
        body += f"\n## Draft Content\n\n{content}\n"
    else:
        body += f"\n## Draft Content\n\n[To be generated by Claude using the generate_sales_post skill]\n"

    body += f"\n## Hashtags\n\n{' '.join(template['hashtags'])}\n"
    body += f"\n## Guidelines\n"
    body += f"- Keep under 1300 characters\n"
    body += f"- Include at least one question\n"
    body += f"- Focus on value, not selling\n"
    body += f"- Professional but approachable tone\n"

    # Create as approval request since posts always need approval
    task_name = topic.replace(" ", "_")[:30]
    filepath = create_task_file("Pending_Approval", "APPROVE_SALESPOST", task_name, metadata, body)

    log_action("Post draft created", f"{filepath.name} — Topic: {topic}", "linkedin_poster")

    return {
        "filepath": str(filepath),
        "filename": filepath.name,
        "topic": topic,
        "template": template_type,
    }


def simulate_publish(post_content: str, topic: str) -> dict:
    """Simulate publishing a post to LinkedIn.

    In dry-run mode: logs to Logs/
    In live mode: would use Playwright to post
    """
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")

    if DRY_RUN:
        log_dir = get_folder("Logs")
        log_file = log_dir / f"linkedin_post_dryrun_{timestamp}.md"
        log_file.write_text(
            f"# LinkedIn Post (DRY-RUN)\n\n"
            f"**Topic:** {topic}\n"
            f"**Timestamp:** {timestamp}\n"
            f"**Status:** Would be published (dry-run)\n\n"
            f"## Content\n\n{post_content}\n",
            encoding="utf-8",
        )
        log_action("DRY-RUN LinkedIn post logged", f"Topic: {topic}", "linkedin_poster")
        return {"status": "dry_run", "log_file": log_file.name}

    # Live mode — Playwright publishing
    try:
        from playwright.sync_api import sync_playwright

        email = os.getenv("LINKEDIN_EMAIL", "")
        password = os.getenv("LINKEDIN_PASSWORD", "")

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=False)
            page = browser.new_page()

            # Login
            page.goto("https://www.linkedin.com/login")
            page.fill("#username", email)
            page.fill("#password", password)
            page.click('button[type="submit"]')
            page.wait_for_load_state("networkidle")

            # Navigate to post creation
            page.goto("https://www.linkedin.com/feed/")
            page.wait_for_load_state("networkidle")

            # Click "Start a post"
            page.click('button:has-text("Start a post")')
            page.wait_for_selector('.ql-editor')

            # Type content
            page.fill('.ql-editor', post_content)

            # Click Post
            page.click('button:has-text("Post")')
            page.wait_for_timeout(3000)

            browser.close()

        log_action("LinkedIn post published", f"Topic: {topic}", "linkedin_poster")
        return {"status": "published", "topic": topic}

    except Exception as e:
        log_error("LinkedIn publish failed", str(e), "linkedin_poster")
        return {"status": "error", "error": str(e)}


def main():
    parser = argparse.ArgumentParser(description="LinkedIn Post Creator")
    parser.add_argument("--topic", type=str, required=True, help="Post topic")
    parser.add_argument(
        "--template",
        choices=list(POST_TEMPLATES.keys()),
        default="thought_leadership",
        help="Post template type",
    )
    parser.add_argument("--audience", type=str, default="Business leaders and tech enthusiasts")
    args = parser.parse_args()

    result = create_post_draft(args.topic, args.template, audience=args.audience)
    print(f"Draft created: {result['filename']}")
    print(f"Awaiting approval in Pending_Approval/")


if __name__ == "__main__":
    main()
